name: devsecops-ci
on: push
jobs:
  ci-start:
    runs-on: ubuntu-latest
    steps:
      - name: start
  code-checks:
    needs: ci-start
    runs-on: ubuntu-latest
    steps:
      - name: setup
      - name: detect-secrets
      - name: compliance-checks
      - name: peer-review
      - name: static-scan
  code-build:
    needs: ci-start
    runs-on: ubuntu-latest
    steps:
      - name: setup
      - name: unit-test
      - name: build-artifact
      - name: sign-artifact
      - name: scan-artifact 
  deploy-checks:
    needs: code-build
    runs-on: ubuntu-latest
    steps:
      - name: setup
      - name: deploy
      - name: dynamic-scan
      - name: acceptance-test 
  deploy-release:
    needs: deploy-checks
    runs-on: ubuntu-latest
    steps:
      - name: run
  code-ci-finish:
    needs: deploy-release
    runs-on: ubuntu-latest
    steps:
      - name: evaluate
      - name: run
